const constants = {
    ADD_DAY: "ADD_DAY",
    REMOVE_DAY: "REMOVE_DAY",
    SET_GOAL: "SET_GOAL",
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    FETCH_RESORT_NAMES: "FETCH_RESORT_NAMES",
    CANCEL_FETCHING: "",
    CHANGE_SUGGESTIONS: "CANCEL_FETCHING",
    CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS",
}

export default constants